name: Docker Image CI (Pull Requests)

on:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - run: cp ./TRENZ.Docs.API/appsettings.example.json ./TRENZ.Docs.API/appsettings.local.json
    - name: Build and test
      run: pushd TRENZ.Docs.API ; docker-compose run -e TrenzDocsApi__OneShot=true --rm api ; popd
